name: rapidvision_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pycocotools
  - opencv=4.11
  - pyqt=5
  - filelock=3.13.1
  - msgpack-python
  - pytorch
  - cpuonly
  - torchvision
  - torchaudio
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
